name: Random Commits to Repos

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  random-commits:
    runs-on: ubuntu-latest
    env:
      USERNAME: abhisheksakibanda
      # Make sure you have AUTO_COMMIT_PAT in repo secrets

    steps:
      - name: Set up random delay
        id: maybe-delay
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Manual run – skipping delay."
            echo "sleep_time=0" >> $GITHUB_OUTPUT
          else
            sleep_time=$(( RANDOM % 86400 ))
            echo "Scheduled run – sleeping for $sleep_time seconds."
            echo "sleep_time=$sleep_time" >> $GITHUB_OUTPUT
          fi

      - name: Sleep before execution (only for scheduled runs)
        run: |
          echo "Sleeping for ${{ steps.maybe-delay.outputs.sleep_time }} seconds..."
          sleep ${{ steps.maybe-delay.outputs.sleep_time }}

      - name: Set Variables
        run: |
          echo "USERNAME=abhisheksakibanda" >> $GITHUB_ENV

      - name: Fetch Public Repos
        id: fetch_repos
        run: |
          repos=$(curl -s -H "Authorization: token ${{ secrets.AUTO_COMMIT_PAT }}" \
            "https://api.github.com/users/${{ env.USERNAME }}/repos?per_page=100" \
            | jq -r '.[] | select(.private==false) | .name')

          echo "$repos" > repos.txt

      - name: Pick Random Repos
        id: pick_random
        run: |
          mapfile -t all_repos < repos.txt
          repo_count=${#all_repos[@]}
          echo "Total public repos: $repo_count"

          n=$(( (RANDOM % 3) + 1 ))  # Pick between 1 and 3 repos
          selected=()
          while [ ${#selected[@]} -lt $n ]; do
            pick=${all_repos[$((RANDOM % repo_count))]}
            [[ " ${selected[*]} " =~ " $pick " ]] || selected+=("$pick")
          done

          echo "Selected repos: ${selected[*]}"
          for repo in "${selected[@]}"; do
            echo "$repo"
          done > selected_repos.txt

      - name: Commit to Random Repos
        run: |
          mapfile -t repos < selected_repos.txt

          for repo in "${repos[@]}"; do
            echo "Cloning and committing to: $repo"

            git clone https://x-access-token:${{ secrets.AUTO_COMMIT_PAT }}@github.com/${{ env.USERNAME }}/$repo.git
            cd $repo

            echo "Commit made at $(date)" >> commit_log.txt

            git config user.name "${{ env.USERNAME }}"
            git config user.email "${{ env.USERNAME }}@users.noreply.github.com"

            git add commit_log.txt
            git commit -m "🤖 Random commit on $(date)"
            git push

            cd ..
            rm -rf $repo
          done
