name: Update Readme with Active Coding Days

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate Active Coding Days
        id: calculate-days
        run: |
          # Set the start date
          start_date="2016-08-10"

          # Calculate the number of days
          start_date_epoch=$(date -d "$start_date" +%s)
          today_epoch=$(date +%s)
          active_days=$(( (today_epoch - start_date_epoch) / 86400 ))

          # Output the result
          echo "::set-output name=active_days::$active_days"

      - name: Update README
        run: |
          # Append or update the README with active days info
          coding_message="I have been actively coding for ${{ steps.calculate-days.outputs.active_days }} days since August 2016."

          # Read the current README content
          if [[ -f README.md ]]; then
            current_content=$(cat README.md)
          else
            current_content=""
          fi

          # Replace or append the coding message
          echo "$current_content" | grep -v "I have been actively coding for" > README.md
          echo "$coding_message" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "abhisheksakibanda"
          git config --global user.email "abhisheksakibanda@gmail.com"
          git add README.md

          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update README with active coding days"
            git push
          fi
