name: Update Readme with Active Coding Duration

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "abhisheksakibanda"
          git config --global user.email "abhisheksakibanda@gmail.com"

      - name: Calculate Active Coding Time
        id: calculate-time
        run: |
          start_date="2016-08-10 00:00:00"
          start_epoch=$(date -d "$start_date" +%s)
          now_epoch=$(date +%s)
          elapsed_seconds=$((now_epoch - start_epoch))

          days=$((elapsed_seconds / 86400))
          hours=$(( (elapsed_seconds % 86400) / 3600 ))
          minutes=$(( (elapsed_seconds % 3600) / 60 ))
          seconds=$((elapsed_seconds % 60))

          echo "days=$days" >> $GITHUB_OUTPUT
          echo "hours=$hours" >> $GITHUB_OUTPUT
          echo "minutes=$minutes" >> $GITHUB_OUTPUT
          echo "seconds=$seconds" >> $GITHUB_OUTPUT

      - name: Make N Random Commits
        run: |
          days=${{ steps.calculate-time.outputs.days }}
          hours=${{ steps.calculate-time.outputs.hours }}
          minutes=${{ steps.calculate-time.outputs.minutes }}
          seconds=${{ steps.calculate-time.outputs.seconds }}

          n=$(( (RANDOM % 5) + 1 ))
          echo "Will make $n commits"

          for i in $(seq 1 $n); do
            message="I have been actively coding for ${days} days, ${hours} hours, ${minutes} minutes, and ${seconds} seconds since August 10, 2016."

            # Remove old line and add new line
            if [[ -f README.md ]]; then
              grep -v "I have been actively coding for" README.md > temp.md || true
            else
              touch temp.md
            fi
            echo "$message" >> temp.md
            mv temp.md README.md

            git add README.md
            git commit -m "Update README with active coding time (Commit $i of $n)"
            git push
            sleep 5
          done
